# Generated by Django 2.1.7 on 2019-03-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('ingredient1', models.CharField(max_length=200)),
                ('ingredient2', models.CharField(blank=True, max_length=200)),
                ('ingredient3', models.CharField(blank=True, max_length=200)),
                ('ingredient4', models.CharField(blank=True, max_length=200)),
                ('ingredient5', models.CharField(blank=True, max_length=200)),
                ('ingredient6', models.CharField(blank=True, max_length=200)),
                ('ingredient7', models.CharField(blank=True, max_length=200)),
                ('ingredient8', models.CharField(blank=True, max_length=200)),
                ('ingredient9', models.CharField(blank=True, max_length=200)),
                ('ingredient10', models.CharField(blank=True, max_length=200)),
                ('ingredient11', models.CharField(blank=True, max_length=200)),
                ('ingredient12', models.CharField(blank=True, max_length=200)),
                ('ingredient13', models.CharField(blank=True, max_length=200)),
                ('ingredient14', models.CharField(blank=True, max_length=200)),
                ('ingredient15', models.CharField(blank=True, max_length=200)),
                ('ingredient10_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient10_type', to='recipe.IngredientType')),
                ('ingredient11_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient11_type', to='recipe.IngredientType')),
                ('ingredient12_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient12_type', to='recipe.IngredientType')),
                ('ingredient13_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient13_type', to='recipe.IngredientType')),
                ('ingredient14_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient14_type', to='recipe.IngredientType')),
                ('ingredient15_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient15_type', to='recipe.IngredientType')),
                ('ingredient1_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient1_type', to='recipe.IngredientType')),
                ('ingredient2_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient2_type', to='recipe.IngredientType')),
                ('ingredient3_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient3_type', to='recipe.IngredientType')),
                ('ingredient4_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient4_type', to='recipe.IngredientType')),
                ('ingredient5_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient5_type', to='recipe.IngredientType')),
                ('ingredient6_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient6_type', to='recipe.IngredientType')),
                ('ingredient7_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient7_type', to='recipe.IngredientType')),
                ('ingredient8_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient8_type', to='recipe.IngredientType')),
                ('ingredient9_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient9_type', to='recipe.IngredientType')),
            ],
        ),
    ]
