# Generated by Django 2.1.7 on 2019-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
