# Generated by Django 2.1.7 on 2019-03-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient10_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient10_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient11_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient11_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient12_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient12_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient13_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient13_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient14_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient14_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient15_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient15_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient2_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient2_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient3_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient3_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient4_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient4_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient5_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient5_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient6_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient6_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient7_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient7_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient8_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient8_type', to='recipe.IngredientType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient9_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient9_type', to='recipe.IngredientType'),
        ),
    ]
