# Generated by Django 2.1.7 on 2019-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20190310_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookTime',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
